name: improwave
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  go_router: ^6.0.0
  shared_preferences: ^2.0.0
  google_nav_bar: ^5.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.20.0
  provider: 
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
  - lib/assets/images/google.png
  - lib/assets/images/logo.png

  uses-material-design: true
