// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0FN2-yrg5z-fADQT1N0VOtwMpIashMM',
    appId: '1:914511310794:web:a4acd947c8cae75fb22933',
    messagingSenderId: '914511310794',
    projectId: 'improwave-2a5f4',
    authDomain: 'improwave-2a5f4.firebaseapp.com',
    storageBucket: 'improwave-2a5f4.appspot.com',
    measurementId: 'G-PJ2D2E2G9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtgSKDR_t9bgZeju8yaPMsOPpQuhtawU',
    appId: '1:914511310794:android:b83d00437b9c9bbab22933',
    messagingSenderId: '914511310794',
    projectId: 'improwave-2a5f4',
    storageBucket: 'improwave-2a5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKt8QJgfTPGgZx0rnCNLGSju6-MKULuqM',
    appId: '1:914511310794:ios:2dddbe92385d9d46b22933',
    messagingSenderId: '914511310794',
    projectId: 'improwave-2a5f4',
    storageBucket: 'improwave-2a5f4.appspot.com',
    iosBundleId: 'com.example.improwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKt8QJgfTPGgZx0rnCNLGSju6-MKULuqM',
    appId: '1:914511310794:ios:2dddbe92385d9d46b22933',
    messagingSenderId: '914511310794',
    projectId: 'improwave-2a5f4',
    storageBucket: 'improwave-2a5f4.appspot.com',
    iosBundleId: 'com.example.improwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz0FN2-yrg5z-fADQT1N0VOtwMpIashMM',
    appId: '1:914511310794:web:7b5190e65f28e788b22933',
    messagingSenderId: '914511310794',
    projectId: 'improwave-2a5f4',
    authDomain: 'improwave-2a5f4.firebaseapp.com',
    storageBucket: 'improwave-2a5f4.appspot.com',
    measurementId: 'G-1N1RE57G3S',
  );

}